import { createContext, useContext, useEffect, useMemo, useState } from "react";

export const languages = [{ code: "en", label: "English" }, { code: "si", label: "සිංහල" }, { code: "ta", label: "தமிழ்" }];
const en = {home:"Home",about:"About",services:"Services",media:"Media",tenders:"Tenders",careers:"Careers",contact:"Contact us",allServices:"All Services",refinery:"Refinery",marketing:"Marketing & Sales",aviation:"Ceypetco Aviation",agro:"Agro Chemicals",lubricants:"Ceypetco Lubricants",servicesLabel:"CEYPETCO SERVICES",servicesTitle:"Powering every sector.",servicesCopy:"Explore our operations and public services.",managementTeam:"Management team",leadership:"Leadership",seeMore:"See more",backTeam:"Back to management team",leadershipLabel:"CEYPETCO LEADERSHIP",professionalProfile:"Professional profile",profileNotFound:"Profile not found",loadingProfile:"Loading profile...",corporation:"Corporation",aboutUs:"About us",ourHistory:"Our history",publicResources:"Public resources",fuelPricing:"Fuel pricing",notices:"Notices",annualReports:"Annual reports",rightToInformation:"Right to Information",headOffice:"Head office",generalLine:"General line",email:"Email",footerCopy:"Delivering dependable petroleum products and energy services that support mobility, industry and national progress.",footerLink:"About the corporation",footerTagline:"Powering progress. Serving the nation.",menu:"Toggle navigation",language:"Language",discover:"Discover",directory:"Management directory",directoryTitle:"Corporate and operational leadership.",directoryCopy:"Official contact directory for Ceypetco's management functions and divisions.",contacts:"contacts",loadingDirectory:"Loading directory...",emptyDirectory:"No directory entries yet",aboutLabel:"Our corporation",aboutTitle:"About Ceypetco",aboutIntro:"Serving Sri Lanka with dependable energy, national infrastructure and trusted public service."};
const si = {...en,home:"මුල් පිටුව",about:"අප ගැන",services:"සේවා",media:"මාධ්‍ය",tenders:"ටෙන්ඩර්",careers:"රැකියා",contact:"අප අමතන්න",allServices:"සියලු සේවා",refinery:"පිරිපහදුව",marketing:"අලෙවි හා විකුණුම්",aviation:"සීපෙට්කෝ ගුවන් සේවා",agro:"කෘෂි රසායන",lubricants:"සීපෙට්කෝ ලිහිසි තෙල්",servicesLabel:"සීපෙට්කෝ සේවා",servicesTitle:"සෑම අංශයකටම බලශක්තිය.",servicesCopy:"අපගේ මෙහෙයුම් සහ මහජන සේවා සොයා බලන්න.",managementTeam:"කළමනාකරණ කණ්ඩායම",leadership:"නායකත්වය",seeMore:"තව බලන්න",backTeam:"කළමනාකරණ කණ්ඩායමට ආපසු",leadershipLabel:"සීපෙට්කෝ නායකත්වය",professionalProfile:"වෘත්තීය පැතිකඩ",profileNotFound:"පැතිකඩ හමු නොවීය",loadingProfile:"පැතිකඩ පූරණය වෙමින්...",corporation:"සංස්ථාව",aboutUs:"අප ගැන",ourHistory:"අපගේ ඉතිහාසය",publicResources:"මහජන සම්පත්",fuelPricing:"ඉන්ධන මිල",notices:"නිවේදන",annualReports:"වාර්ෂික වාර්තා",rightToInformation:"තොරතුරු දැනගැනීමේ අයිතිය",headOffice:"ප්‍රධාන කාර්යාලය",generalLine:"ප්‍රධාන දුරකථනය",email:"විද්‍යුත් තැපෑල",footerCopy:"ප්‍රවාහනය, කර්මාන්තය සහ ජාතික ප්‍රගතිය සඳහා විශ්වාසනීය ඛනිජ තෙල් නිෂ්පාදන හා බලශක්ති සේවා සැපයීම.",footerLink:"සංස්ථාව ගැන",footerTagline:"ප්‍රගතියට බලය. ජාතියට සේවය.",menu:"සංචාලනය විවෘත කරන්න",language:"භාෂාව",discover:"හඳුනාගන්න",directory:"කළමනාකරණ නාමාවලිය",directoryTitle:"ආයතනික සහ මෙහෙයුම් නායකත්වය.",directoryCopy:"සීපෙට්කෝ කළමනාකරණ කාර්යයන් සහ අංශ සඳහා නිල සම්බන්ධතා නාමාවලිය.",contacts:"සම්බන්ධතා",loadingDirectory:"නාමාවලිය පූරණය වෙමින්...",emptyDirectory:"නාමාවලි ඇතුළත් කිරීම් නොමැත",aboutLabel:"අපගේ සංස්ථාව",aboutTitle:"සීපෙට්කෝ ගැන",aboutIntro:"විශ්වාසනීය බලශක්තිය, ජාතික යටිතල පහසුකම් සහ විශ්වාසවන්ත මහජන සේවය සමඟ ශ්‍රී ලංකාවට සේවය කිරීම."};
const ta = {...en,home:"முகப்பு",about:"எங்களைப் பற்றி",services:"சேவைகள்",media:"ஊடகம்",tenders:"கேள்விப்பத்திரங்கள்",careers:"தொழில் வாய்ப்புகள்",contact:"தொடர்பு கொள்ளுங்கள்",allServices:"அனைத்து சேவைகள்",refinery:"சுத்திகரிப்பு நிலையம்",marketing:"சந்தைப்படுத்தல் மற்றும் விற்பனை",aviation:"சிபெட்கோ விமான சேவை",agro:"விவசாய இரசாயனங்கள்",lubricants:"சிபெட்கோ மசகு எண்ணெய்கள்",servicesLabel:"சிபெட்கோ சேவைகள்",servicesTitle:"ஒவ்வொரு துறைக்கும் ஆற்றல்.",servicesCopy:"எங்கள் செயல்பாடுகள் மற்றும் பொதுச் சேவைகளை அறியுங்கள்.",managementTeam:"நிர்வாகக் குழு",leadership:"தலைமைத்துவம்",seeMore:"மேலும் பார்க்க",backTeam:"நிர்வாகக் குழுவிற்கு திரும்பு",leadershipLabel:"சிபெட்கோ தலைமைத்துவம்",professionalProfile:"தொழில்முறை சுயவிவரம்",profileNotFound:"சுயவிவரம் கிடைக்கவில்லை",loadingProfile:"சுயவிவரம் ஏற்றப்படுகிறது...",corporation:"கூட்டுத்தாபனம்",aboutUs:"எங்களைப் பற்றி",ourHistory:"எமது வரலாறு",publicResources:"பொது வளங்கள்",fuelPricing:"எரிபொருள் விலை",notices:"அறிவித்தல்கள்",annualReports:"வருடாந்த அறிக்கைகள்",rightToInformation:"தகவல் அறியும் உரிமை",headOffice:"தலைமை அலுவலகம்",generalLine:"பொது தொலைபேசி",email:"மின்னஞ்சல்",footerCopy:"போக்குவரத்து, தொழில்துறை மற்றும் தேசிய முன்னேற்றத்திற்கு நம்பகமான பெற்றோலியப் பொருட்களையும் ஆற்றல் சேவைகளையும் வழங்குதல்.",footerLink:"கூட்டுத்தாபனம் பற்றி",footerTagline:"முன்னேற்றத்திற்கு ஆற்றல். நாட்டிற்கு சேவை.",menu:"வழிசெலுத்தலைத் திறக்கவும்",language:"மொழி",discover:"அறியுங்கள்",directory:"நிர்வாக அடைவு",directoryTitle:"நிறுவன மற்றும் செயல்பாட்டுத் தலைமைத்துவம்.",directoryCopy:"சிபெட்கோவின் நிர்வாகச் செயல்பாடுகள் மற்றும் பிரிவுகளுக்கான அதிகாரப்பூர்வ தொடர்பு அடைவு.",contacts:"தொடர்புகள்",loadingDirectory:"அடைவு ஏற்றப்படுகிறது...",emptyDirectory:"அடைவு பதிவுகள் எதுவும் இல்லை",aboutLabel:"எமது கூட்டுத்தாபனம்",aboutTitle:"சிபெட்கோ பற்றி",aboutIntro:"நம்பகமான ஆற்றல், தேசிய உட்கட்டமைப்பு மற்றும் நம்பிக்கையான பொதுச் சேவையுடன் இலங்கைக்கு சேவையாற்றுதல்."};
const messages = { en, si, ta };
const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => { const saved=localStorage.getItem("ceypetco_language"); return messages[saved]?saved:"en"; });
  useEffect(() => { localStorage.setItem("ceypetco_language", language); document.documentElement.lang=language; }, [language]);
  const value=useMemo(() => ({language,setLanguage,languages,t:(key)=>messages[language]?.[key]||en[key]||key}), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
export const useLanguage = () => { const value=useContext(LanguageContext); if(!value) throw new Error("LanguageProvider is missing"); return value; };
